In [2]:
import numpy as np
fuckery = np.genfromtxt("/home/data/madlab/data/mri/wmaze/preproc/WMAZE_001/noise/motion_regressor00.txt")
print len(fuckery)

200


In [4]:
import nibabel as nb

more_fuckery = nb.load('/home/data/madlab/data/mri/wmaze/preproc/WMAZE_001/func/smoothed_fullspectrum/_maskfunc20/corr_wmaze_01_dtype_despike_bet_smooth_mask.nii.gz')
print more_fuckery

<class 'nibabel.nifti1.Nifti1Image'>
data shape (96, 96, 42, 200)
affine: 
[[ -2.48171425e+00   5.10274842e-02   3.56942683e-01   1.11510391e+02]
 [ -1.06421225e-01   2.15781951e+00  -1.50945055e+00  -5.21768532e+01]
 [  2.82434911e-01   1.26143217e+00   2.56764340e+00  -1.02998154e+02]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]
metadata:
<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : 
db_name         : 
extents         : 0
session_error   : 0
regular         : r
dim_info        : 0
dim             : [  4  96  96  42 200   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : float64
bitpix          : 64
slice_start     : 0
pixdim          : [-1.         2.5        2.5        2.9997735  1.         0.         0.         0.       ]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_

In [1]:
import nibabel as nb

more_fuckery2 = nb.load('/home/data/madlab/data/mri/wmaze/scndlvl/wmaze_MRthesis/fixed_before_conditional/model5orig_3-2/WMAZE_001/fixedfx/cope_all_before_B_corr.nii.gz')
print more_fuckery2

<class 'nibabel.nifti1.Nifti1Image'>
data shape (96, 96, 42)
affine: 
[[-2.48171425e+00  5.10274842e-02  3.56942713e-01  1.11510391e+02]
 [-1.06421217e-01  2.15781951e+00 -1.50945044e+00 -5.21768532e+01]
 [ 2.82434881e-01  1.26143217e+00  2.56764317e+00 -1.02998154e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
metadata:
<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : 
db_name         : 
extents         : 0
session_error   : 0
regular         : r
dim_info        : 0
dim             : [ 3 96 96 42  1  1  1  1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : estimate
datatype        : float32
bitpix          : 32
slice_start     : 0
pixdim          : [-1.         2.5        2.5        2.9997735  1.         0.
  0.         0.       ]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 10
cal_max        

In [3]:
import nibabel as nb

more_fuckery2 = nb.load('/home/data/madlab/data/mri/wmaze/scndlvl/wmaze_MRthesis/fixed_before_conditional/model3/WMAZE_001/fixedfx/cope_all_before_B_corr.nii.gz')
print more_fuckery2

<class 'nibabel.nifti1.Nifti1Image'>
data shape (96, 96, 42)
affine: 
[[-2.48171425e+00  5.10274842e-02  3.56942713e-01  1.11510391e+02]
 [-1.06421217e-01  2.15781951e+00 -1.50945044e+00 -5.21768532e+01]
 [ 2.82434881e-01  1.26143217e+00  2.56764317e+00 -1.02998154e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
metadata:
<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : 
db_name         : 
extents         : 0
session_error   : 0
regular         : r
dim_info        : 0
dim             : [ 3 96 96 42  1  1  1  1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : estimate
datatype        : float32
bitpix          : 32
slice_start     : 0
pixdim          : [-1.         2.5        2.5        2.9997735  1.         0.
  0.         0.       ]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 10
cal_max        